os: linux
dist: bionic

language: php
php: 7.4
node_js: 12.13.1

branches:
  only:
    - master
    - /^release\/.*/
    - /^feature\/.*/

cache:
  directories:
    - build
    - node_modules
    - vendor

install:
  - composer install
  - npm install

before_script:
- bash tests/bin/install.sh crowdsignal_forms_tests root '' localhost latest true

jobs:
  include:
    - stage: lint
      script: vendor/bin/phpcs --ignore="*/docker/*" .
    - stage: lint
      script: npm run lint:js
    - stage: lint
      script: npm run lint:styles
    - stage: test
    #   script: vendor/bin/phpunit
    # - stage: test
      script: npm run test
    - stage: build
      script: npm run build:editor
    - stage: build
      script: npm run build:styles
