# This is a basic workflow to help you get started with Actions

name: Create nightly build release

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: Branch to build, defaults to master
        required: true
        default: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "Triggered by ${{ github.event_name }}"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.buildBranch }}

      - name: Fork
        run: git checkout -b nightly_build

      - name: Install
        run: |
          npm install
          composer update
          composer install

      #
      # - name: Build
      #   run: |
      #     npm run build:styles
      #     npm run build:apifetch
      #     npm run build:editor
      #     npm run build:poll
      #     npm run build:vote
      #     npm run build:applause
      #     npm run build:nps
      #   env:
      #     NODE_ENV: production
      #
      #   - name: Package for release
      #     run: |
      #       scripts/makepot.sh
      #       scripts/package-for-release.sh
      #
      # - name: Create nightly build release
      #   uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     automatic_release_tag: nightly_build
      #     prerelease: true
      #     title: Development Build
      #     files: ./release/crowdsignal-forms.nightly_build.zip
