# This is a basic workflow to help you get started with Actions

name: Create nightly build release

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: Branch to build
        required: true
        default: master
      releaseName:
        description: Named release
        required: true
        default: nightly_build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Trigger"
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Setup PHP 7.4 with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Setup Node version 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.buildBranch }}

      - name: Fork
        run: git checkout -b nightly_build

      - name: NPM install
        run: npm install

      - name: Composer install
        run: composer install

      - name: Build
        run: make client
        env:
          NODE_ENV: production

      - name: Package for release
        run: |
          scripts/makepot.sh
          scripts/package-for-release.sh

      - name: Create nightly build release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.releaseName }}
          prerelease: true
          title: Development Build
          files: release/crowdsignal-forms.${{ github.event.inputs.releaseName }}.zip
